// src/constants/colleges.ts
export const COLLEGES = [
  "Gosavi Polytechnic",
  "GPT Thane",
  "Gramin Polytechnic",
  "Guru Gobind Singh Polytechnic",
  "GV Acharya",
  "Jondhale Ambernath",
  "Jondhale Asangaon",
  "Jondhale Dombivli",
  "JSPM University",
  "KCE College",
  "Late Vasantdada Polytechnic",
  "M.H Saboo Siddik Polytechnic",
  "Mucchala Polytechnic",
  "Samarth Polytechnic",
  "Sanjeevan Group of Polytechnic",
  "TB Girwalkar",
  "TSSM Bhivrabai",
  "Venutai Chavan Poly",
  "Vidya Vikas VVP",
  "Vidyalankar Polytechnic",
  "Vivekanand Polytechnic Chembur",
  "VPM Polytechnic",
  "Wainganga College",
  "Zeal Polytechnic",
  "Abhay Singh Raje Polytechnic",
  "Adarsh Institute of Technology",
  "AR Kalsekar",
  "Armiet College",
  "Arvind Gavali Polytechnic",
  "Ashok Institute",
  "Atma Malik College",
  "Ballarpur Institute",
  "Bharati Vidyapeeth",
  "Bhivrabai Sawant Polytechnic",
  "Chh Shivaji Polytechnic Vaduj",
  "CSMSS Polytechnic",
  "Delhi Skill and Entrepreneurship University",
  "Devi Mahalaxmi Polytechnic",
  "Dilkap College",
  "Dr RN Lahoti Polytechnic",
  "Nashik institute technology",
  "Government polytechnic Gondia",
  "Trimurti Institute of Technical education",
  "DY Patil Ambi, Pune",
].sort(); 